services:
  - name: laravel-app
    type: web
    env: docker  # Docker asosida ishlash
    buildCommand: "composer install --optimize-autoloader --no-dev && php artisan config:cache && php artisan route:cache && php artisan view:cache"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    dockerfilePath: ./Dockerfile  # Dockerfile joylashgan joy
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: <your-app-key>  # php artisan key:generate orqali yarating
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: <your-database-host>
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: <your-database-name>
      - key: DB_USERNAME
        value: <your-database-username>
      - key: DB_PASSWORD
        value: <your-database-password>
    plan: free  # Render Free Rejasidan foydalanish
    disk:
      name: persistent_data
      mountPath: /var/www/storage  # Laravel uchun kesh va saqlash uchun joy
      sizeGB: 1  # Minimal disk hajmi
